{{ config(materialized='table') }}

SELECT 
  ORDER_ID, 
  CUSTOMER_ID, 
  ORDER_DATE, 
  STATUS, 
  TOTAL_AMOUNT, 
  CHANNEL, 
  CREATED_AT, 
  UPDATED_AT, 
  _SNOWFLAKE_INSERTED_AT, 
  _SNOWFLAKE_UPDATED_AT,
  DISCOUNT_CODE
FROM 
  {{ source('bronze', 'orders') }}
WHERE 
  (_SNOWFLAKE_DELETED IS NULL OR _SNOWFLAKE_DELETED = FALSE)
QUALIFY 
  ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY _SNOWFLAKE_UPDATED_AT DESC) = 1