{{
  config(
    database = var('db_name'),
    schema   = 'SILVER'
  )
}}

SELECT
    ITEM_ID,
    ORDER_ID,
    PRODUCT_ID,
    PRODUCT_NAME,
    QUANTITY,
    UNIT_PRICE,
    CREATED_AT,
    _SNOWFLAKE_INSERTED_AT,
    _SNOWFLAKE_UPDATED_AT
FROM {{ source('bronze', 'order_items') }}
WHERE (_SNOWFLAKE_DELETED IS NULL OR _SNOWFLAKE_DELETED = FALSE)
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY ITEM_ID
    ORDER BY _SNOWFLAKE_UPDATED_AT DESC
) = 1