{{ config(database=var('db_name'), schema='SILVER') }}
SELECT
    SHIPMENT_ID
    , CREATED_AT
    , STATUS
    , ORDER_ID
    , CARRIER
    , TRACKING_NUMBER
    , SHIPPED_AT
FROM {{ source('bronze', 'shipments') }}
WHERE (_SNOWFLAKE_DELETED IS NULL OR _SNOWFLAKE_DELETED = FALSE)
QUALIFY ROW_NUMBER() OVER (PARTITION BY SHIPMENT_ID ORDER BY _SNOWFLAKE_UPDATED_AT DESC) = 1