-- =============================================================
-- 15_run_as_pipeline.sql
-- Hardening: run the pipeline under the least-privilege
-- SELFHEALING_PIPELINE role instead of ACCOUNTADMIN.
--
-- Design:
--   • SELFHEALING_PIPELINE owns and runs the tasks.
--   • It has SCOPED grants only — read PROD, write DEV +
--     GENERATED_CODE, call the pipeline procs.
--   • It does NOT have CREATE DATABASE. The DEV clone is done
--     by REFRESH_DEV_ENVIRONMENT (EXECUTE AS OWNER), which the
--     pipeline role is merely allowed to CALL — so the
--     privileged clone happens in a controlled, fixed way.
--
-- Run as ACCOUNTADMIN AFTER all procs and tasks exist
-- (i.e. after 13, and 14 if running the full version).
-- =============================================================

USE ROLE ACCOUNTADMIN;

-- ── Privileges needed to drive the pipeline ───────────────────
GRANT EXECUTE TASK ON ACCOUNT                       TO ROLE SELFHEALING_PIPELINE;
GRANT USAGE ON WAREHOUSE SELFHEALING_WH             TO ROLE SELFHEALING_PIPELINE;
GRANT USAGE ON DATABASE  SELFHEALING_PROD           TO ROLE SELFHEALING_PIPELINE;
GRANT USAGE ON SCHEMA    SELFHEALING_PROD.CONFIG    TO ROLE SELFHEALING_PIPELINE;
GRANT USAGE ON SCHEMA    SELFHEALING_PROD.BRONZE    TO ROLE SELFHEALING_PIPELINE;

-- Read PROD schema metadata + data for impact analysis / drift detection
GRANT SELECT ON ALL TABLES    IN SCHEMA SELFHEALING_PROD.BRONZE TO ROLE SELFHEALING_PIPELINE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SELFHEALING_PROD.BRONZE TO ROLE SELFHEALING_PIPELINE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_PIPELINE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_PIPELINE;

-- Allow the role to CALL the pipeline procs (privileged work is
-- encapsulated in EXECUTE AS OWNER procs — the role never gets
-- CREATE DATABASE or other broad grants directly).
GRANT USAGE ON ALL PROCEDURES    IN SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_PIPELINE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_PIPELINE;

-- ── Transfer task ownership so tasks RUN AS the pipeline role ──
-- Tasks execute with their owner's privileges. Revoking back to
-- ACCOUNTADMIN is not needed; COPY CURRENT GRANTS keeps schedules.
-- Tasks must be SUSPENDED before ownership can be transferred.
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.SCHEMA_DRIFT_DETECTOR SUSPEND;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.PIPELINE_ROOT         SUSPEND;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.RUN_DEV_TEST          SUSPEND;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.COMMIT_AND_MR         SUSPEND;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.PIPELINE_FINALIZER    SUSPEND;

GRANT OWNERSHIP ON TASK SELFHEALING_PROD.CONFIG.SCHEMA_DRIFT_DETECTOR
  TO ROLE SELFHEALING_PIPELINE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TASK SELFHEALING_PROD.CONFIG.PIPELINE_ROOT
  TO ROLE SELFHEALING_PIPELINE COPY CURRENT GRANTS;

-- Full-version DAG tasks (skipped harmlessly if not created)
GRANT OWNERSHIP ON TASK SELFHEALING_PROD.CONFIG.RUN_DEV_TEST
  TO ROLE SELFHEALING_PIPELINE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TASK SELFHEALING_PROD.CONFIG.COMMIT_AND_MR
  TO ROLE SELFHEALING_PIPELINE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TASK SELFHEALING_PROD.CONFIG.PIPELINE_FINALIZER
  TO ROLE SELFHEALING_PIPELINE COPY CURRENT GRANTS;

-- ── Make the role assumable by admins ─────────────────────────
GRANT ROLE SELFHEALING_PIPELINE TO ROLE SYSADMIN;

-- ── Resume tasks under the new owner (leaf-to-root) ───────────
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.PIPELINE_FINALIZER  RESUME;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.COMMIT_AND_MR       RESUME;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.RUN_DEV_TEST        RESUME;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.PIPELINE_ROOT       RESUME;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.SCHEMA_DRIFT_DETECTOR RESUME;
