-- =============================================================
-- 15_run_as_pipeline.sql
-- Hardening: run the pipeline under the least-privilege
-- SELFHEALING_PIPELINE role instead of ACCOUNTADMIN.
--
-- Design:
--   • SELFHEALING_PIPELINE owns and runs the tasks.
--   • It has SCOPED grants only — read PROD, write DEV +
--     GENERATED_CODE, call the pipeline procs.
--   • It does NOT have CREATE DATABASE. The DEV clone is done
--     by REFRESH_DEV_ENVIRONMENT (EXECUTE AS OWNER), which the
--     pipeline role is merely allowed to CALL — so the
--     privileged clone happens in a controlled, fixed way.
--
-- Run as ACCOUNTADMIN AFTER all procs and tasks exist
-- (i.e. after 13, and 14 if running the full version).
-- =============================================================

USE ROLE ACCOUNTADMIN;

-- ── Privileges needed to drive the pipeline ───────────────────
GRANT EXECUTE TASK ON ACCOUNT                       TO ROLE SELFHEALING_PIPELINE;
GRANT USAGE ON WAREHOUSE SELFHEALING_WH             TO ROLE SELFHEALING_PIPELINE;
GRANT USAGE ON DATABASE  SELFHEALING_PROD           TO ROLE SELFHEALING_PIPELINE;
GRANT USAGE ON SCHEMA    SELFHEALING_PROD.CONFIG    TO ROLE SELFHEALING_PIPELINE;
GRANT USAGE ON SCHEMA    SELFHEALING_PROD.BRONZE    TO ROLE SELFHEALING_PIPELINE;

-- The pipeline role re-creates the DAG edges (full version) under its own
-- ownership after the transfer below, and (full) creates the DEV-test dbt
-- project at runtime — so it needs CREATE TASK and CREATE DBT PROJECT.
GRANT CREATE TASK        ON SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_PIPELINE;
GRANT CREATE DBT PROJECT ON SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_PIPELINE;

-- Read PROD schema metadata + data for impact analysis / drift detection
GRANT SELECT ON ALL TABLES    IN SCHEMA SELFHEALING_PROD.BRONZE TO ROLE SELFHEALING_PIPELINE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SELFHEALING_PROD.BRONZE TO ROLE SELFHEALING_PIPELINE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_PIPELINE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_PIPELINE;

-- Allow the role to CALL the pipeline procs (privileged work is
-- encapsulated in EXECUTE AS OWNER procs — the role never gets
-- CREATE DATABASE or other broad grants directly).
GRANT USAGE ON ALL PROCEDURES    IN SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_PIPELINE;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA SELFHEALING_PROD.CONFIG TO ROLE SELFHEALING_PIPELINE;

-- ── Transfer task ownership so tasks RUN AS the pipeline role ──
-- Tasks execute with their owner's privileges. Tasks must be SUSPENDED
-- before ownership can transfer, and GRANT OWNERSHIP has no IF EXISTS —
-- so each transfer is wrapped to skip tasks that don't exist (trial has
-- only SCHEMA_DRIFT_DETECTOR + PIPELINE_ROOT; the full DAG adds three
-- more). COPY CURRENT GRANTS preserves schedules.
EXECUTE IMMEDIATE $$
BEGIN
    BEGIN
        ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.SCHEMA_DRIFT_DETECTOR SUSPEND;
        GRANT OWNERSHIP ON TASK SELFHEALING_PROD.CONFIG.SCHEMA_DRIFT_DETECTOR
            TO ROLE SELFHEALING_PIPELINE COPY CURRENT GRANTS;
    EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN
        ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.PIPELINE_ROOT SUSPEND;
        GRANT OWNERSHIP ON TASK SELFHEALING_PROD.CONFIG.PIPELINE_ROOT
            TO ROLE SELFHEALING_PIPELINE COPY CURRENT GRANTS;
    EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN
        ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.RUN_DEV_TEST SUSPEND;
        GRANT OWNERSHIP ON TASK SELFHEALING_PROD.CONFIG.RUN_DEV_TEST
            TO ROLE SELFHEALING_PIPELINE COPY CURRENT GRANTS;
    EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN
        ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.COMMIT_AND_MR SUSPEND;
        GRANT OWNERSHIP ON TASK SELFHEALING_PROD.CONFIG.COMMIT_AND_MR
            TO ROLE SELFHEALING_PIPELINE COPY CURRENT GRANTS;
    EXCEPTION WHEN OTHER THEN NULL; END;
    BEGIN
        ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.PIPELINE_FINALIZER SUSPEND;
        GRANT OWNERSHIP ON TASK SELFHEALING_PROD.CONFIG.PIPELINE_FINALIZER
            TO ROLE SELFHEALING_PIPELINE COPY CURRENT GRANTS;
    EXCEPTION WHEN OTHER THEN NULL; END;
END;
$$;

-- ── Make the role assumable by admins ─────────────────────────
GRANT ROLE SELFHEALING_PIPELINE TO ROLE SYSADMIN;

-- ── Rebuild DAG edges + resume, AS the pipeline role ──────────
-- Transferring task ownership one-by-one (above) severs the AFTER/FINALIZE
-- edges of a task DAG: Snowflake requires every task in a DAG to share one
-- owner, and the intermediate mixed-owner state drops the predecessor and
-- finalizer links (the tasks become bare and cannot be resumed). So we now
-- switch to the pipeline role — which owns all the tasks post-transfer — and
-- re-create the edges, then resume leaf-to-root.
USE ROLE SELFHEALING_PIPELINE;
USE WAREHOUSE SELFHEALING_WH;

-- Full version only: re-create RUN_DEV_TEST → COMMIT_AND_MR and the finalizer.
-- Guarded on RUN_DEV_TEST existing, so the trial path (which has none of these
-- tasks, nor the COMMIT_TO_GITHUB / HANDLE_TEST_FAILURE procs) skips it.
EXECUTE IMMEDIATE $$
DECLARE
    full_dag INT;
BEGIN
    SHOW TASKS LIKE 'RUN_DEV_TEST' IN SCHEMA SELFHEALING_PROD.CONFIG;
    full_dag := (SELECT COUNT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
    IF (full_dag > 0) THEN
        -- Suspend before re-creating (root must be suspended to alter its DAG).
        ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.PIPELINE_FINALIZER SUSPEND;
        ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.COMMIT_AND_MR      SUSPEND;
        ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.RUN_DEV_TEST       SUSPEND;
        ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.PIPELINE_ROOT      SUSPEND;
        CREATE OR REPLACE TASK SELFHEALING_PROD.CONFIG.RUN_DEV_TEST
            WAREHOUSE = SELFHEALING_WH
            AFTER     SELFHEALING_PROD.CONFIG.PIPELINE_ROOT
        AS
            EXECUTE DBT PROJECT SELFHEALING_PROD.CONFIG.SELFHEALING
                ARGS = 'run --vars "{db_name: SELFHEALING_DEV}" --target dev';
        CREATE OR REPLACE TASK SELFHEALING_PROD.CONFIG.COMMIT_AND_MR
            WAREHOUSE = SELFHEALING_WH
            AFTER     SELFHEALING_PROD.CONFIG.RUN_DEV_TEST
        AS
            CALL SELFHEALING_PROD.CONFIG.COMMIT_TO_GITHUB();
        CREATE OR REPLACE TASK SELFHEALING_PROD.CONFIG.PIPELINE_FINALIZER
            WAREHOUSE = SELFHEALING_WH
            FINALIZE  = SELFHEALING_PROD.CONFIG.PIPELINE_ROOT
        AS
            CALL SELFHEALING_PROD.CONFIG.HANDLE_TEST_FAILURE();
    END IF;
END;
$$;

-- Resume leaf-to-root (as the pipeline role, which owns the tasks + has EXECUTE TASK)
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.PIPELINE_FINALIZER  RESUME;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.COMMIT_AND_MR       RESUME;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.RUN_DEV_TEST        RESUME;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.PIPELINE_ROOT       RESUME;
ALTER TASK IF EXISTS SELFHEALING_PROD.CONFIG.SCHEMA_DRIFT_DETECTOR RESUME;

USE ROLE ACCOUNTADMIN;
