"""
materialise_in_dev.py

For a given event_id:
  1. Read all generated SQL from <PROD_DB>.CONFIG.GENERATED_CODE
  2. Back up the original model files
  3. Write generated SQL to each model file path
  4. Open PR immediately (PR-first)
  5. Deploy a new dbt project version (prod version untouched)
  6. Run dbt against DEV_DB using --select source:bronze.<table>+
  7. Parse dbt output — update GENERATED_CODE.test_status per model
  8. Post CI result as PR comment; set pipeline_status CI_PASSED/CI_FAILED

Usage:
  python3 config/materialise_in_dev.py <event_id>

Environment variables (REQUIRED — script exits if not set):
  SNOWFLAKE_CONNECTION_SQL  Snow CLI connection name        e.g. my_connection
  SNOWFLAKE_CONNECTION_PY   Python connector connection     e.g. my_connection_pat
  GITHUB_REPO               GitHub repo in org/name format  e.g. my-org/my-repo

Environment variables (optional — sensible defaults provided):
  DBT_DIR                   Path to dbt project directory   (default: ../dbt relative to this script)
  DBT_PROJECT               Snowflake dbt project FQN       (default: PLATFORM_REGISTRY.DBT.SELFHEALING_TEST)
  PROD_DB                   Production database name        (default: SELFHEALING_PROD)
  DEV_DB                    DEV clone database name         (default: SELFHEALING_DEV)
  GITHUB_PAT                GitHub personal access token    (required for PR + comments)
"""

import subprocess, json, sys, os, re, requests
import snowflake.connector

def _require(name):
    val = os.environ.get(name)
    if not val:
        print(f"ERROR: environment variable {name} is not set")
        sys.exit(1)
    return val

CONNECTION_SQL = _require('SNOWFLAKE_CONNECTION_SQL')
CONNECTION_PY  = _require('SNOWFLAKE_CONNECTION_PY')
REPO           = _require('GITHUB_REPO')
DBT_DIR        = os.environ.get('DBT_DIR', os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'dbt'))
DBT_PROJECT    = os.environ.get('DBT_PROJECT', 'PLATFORM_REGISTRY.DBT.SELFHEALING_TEST')
PROD_DB        = os.environ.get('PROD_DB', 'SELFHEALING_PROD')
DEV_DB         = os.environ.get('DEV_DB',  'SELFHEALING_DEV')
GITHUB_API     = 'https://api.github.com'


def gh_headers(token):
    return {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json',
    }


def open_pr(token, branch_name, change_type, table_name, column_name, artifacts):
    artifact_list = '\n'.join(f'- `{a[0]}` ({a[3]})' for a in artifacts)
    pr_title = f'[schema-change] {change_type} on {table_name}.{column_name}'.rstrip('.')
    pr_body = f"""## Schema Change: {change_type}

**Table:** `BRONZE.{table_name}`  **Column:** `{column_name or '(new table)'}`

## Impacted Artifacts
{artifact_list}

## CI Status
_dbt validation is running against a zero-copy clone of {PROD_DB}._  
_Results will be posted as a comment below._

> Auto-generated by Snowflake schema drift pipeline.
"""
    r = requests.post(
        f'{GITHUB_API}/repos/{REPO}/pulls',
        headers=gh_headers(token),
        json={'title': pr_title, 'head': branch_name, 'base': 'main', 'body': pr_body}
    )
    if r.status_code == 422:  # already open
        existing = requests.get(
            f'{GITHUB_API}/repos/{REPO}/pulls',
            headers=gh_headers(token),
            params={'head': f'{REPO.split("/")[0]}:{branch_name}', 'state': 'open'}
        )
        return existing.json()[0]['html_url'] if existing.ok and existing.json() else ''
    r.raise_for_status()
    return r.json()['html_url']


def post_pr_comment(token, pr_url, body):
    m = re.search(r'/pull/(\d+)', pr_url)
    if not m:
        return
    r = requests.post(
        f'{GITHUB_API}/repos/{REPO}/issues/{m.group(1)}/comments',
        headers=gh_headers(token),
        json={'body': body}
    )
    r.raise_for_status()

(query):
    result = subprocess.run(
        ["snow", "sql", "-c", CONNECTION_SQL, "--format", "json", "-q", query],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"snow sql failed:\n{result.stderr[:500]}")
    return json.loads(result.stdout) if result.stdout.strip() else []


def dbt_deploy():
    result = subprocess.run(
        ["snow", "dbt", "deploy", DBT_PROJECT,
         "--source", DBT_DIR, "--connection", CONNECTION_SQL],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"snow dbt deploy failed:\n{result.stderr[:500]}")
    print(f"  dbt project deployed: {result.stdout.strip().splitlines()[-1]}")


def dbt_run(selector, dev_db):
    """Run dbt against DEV. Returns (passed, stdout)."""
    query = (
        f"EXECUTE DBT PROJECT {DBT_PROJECT} "
        f"ARGS = 'run --select {selector} "
        f"--vars \"{{db_name: {dev_db}}}\" "
        f"--target prod'"
    )
    result = subprocess.run(
        ["snow", "sql", "-c", CONNECTION_SQL, "-q", query],
        capture_output=True, text=True
    )
    stdout = result.stdout + result.stderr
    passed = result.returncode == 0 and "ERROR=0" in stdout
    return passed, stdout


def parse_model_results(stdout):
    """
    Extract per-model pass/fail from dbt stdout.
    dbt prints lines like:
      OK created sql table model SILVER.customers ... [SUCCESS 1 in 2.34s]
      ERROR creating sql table model GOLD.orders_daily ... [ERROR]
    Returns dict: {model_name: ('PASS'|'FAIL', detail)}
    """
    results = {}
    for line in stdout.splitlines():
        line = line.strip().lstrip('|').strip()
        if 'OK created' in line or 'SUCCESS' in line:
            for keyword in ['SILVER.', 'GOLD.']:
                if keyword in line.upper():
                    name = line.upper().split(keyword)[-1].split()[0].lower()
                    schema = keyword.rstrip('.').lower()
                    results[f"{schema}.{name}"] = ('PASS', line.strip())
        elif 'ERROR creating' in line or 'Database Error' in line:
            for keyword in ['SILVER.', 'GOLD.']:
                if keyword in line.upper():
                    name = line.upper().split(keyword)[-1].split()[0].lower()
                    schema = keyword.rstrip('.').lower()
                    results[f"{schema}.{name}"] = ('FAIL', line.strip())
    return results


def run(event_id):
    conn = snowflake.connector.connect(connection_name=CONNECTION_PY)
    cur  = conn.cursor()

    # ── 1. Fetch event details ─────────────────────────────────
    cur.execute(f"""
        SELECT TABLE_NAME, CHANGE_TYPE, COLUMN_NAME, BRANCH_NAME
        FROM {PROD_DB}.CONFIG.SCHEMA_CHANGE_EVENTS
        WHERE EVENT_ID = '{event_id}'
    """)
    row = cur.fetchone()
    if not row:
        print(f"Event {event_id} not found")
        return
    table_name, change_type, column_name, branch_name = row[0].lower(), row[1], row[2] or '', row[3] or ''
    print(f"\nEvent: {change_type} on {table_name.upper()}")

    # ── 2. Fetch generated code from PROD ─────────────────────
    cur.execute(f"""
        SELECT ARTIFACT_NAME, FILE_PATH, GENERATED_SQL, ACTION
        FROM {PROD_DB}.CONFIG.GENERATED_CODE
        WHERE EVENT_ID = '{event_id}'
        ORDER BY GENERATED_AT
    """)
    artifacts = cur.fetchall()
    if not artifacts:
        print("No generated code found — run GENERATE_ARTIFACT_CODE first")
        return
    print(f"Found {len(artifacts)} generated artifact(s):")
    for name, path, _, action in artifacts:
        print(f"  {action}: {name} \u2192 {path}")

    # ── 3. Back up originals and write generated files ────────
    backups = {}
    print("\nWriting generated SQL to model files...")
    for artifact_name, file_path, generated_sql, action in artifacts:
        full_path = os.path.join(DBT_DIR, file_path)
        if os.path.exists(full_path):
            with open(full_path) as f:
                backups[full_path] = f.read()
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, 'w') as f:
            f.write(generated_sql)
        print(f"  Written: {file_path}")

    # ── 4. Open PR immediately (PR-first) ─────────────────────
    token  = os.environ.get('GITHUB_PAT', '')
    pr_url = ''
    if token and branch_name:
        print(f"\nOpening PR on branch {branch_name}...")
        try:
            pr_url = open_pr(token, branch_name, change_type, table_name, column_name, artifacts)
            print(f"  PR opened: {pr_url}")
            pr_url_esc = pr_url.replace("'", "''")
            cur.execute(f"""
                UPDATE {PROD_DB}.CONFIG.SCHEMA_CHANGE_EVENTS
                SET pipeline_status = 'PR_OPEN', mr_url = '{pr_url_esc}'
                WHERE EVENT_ID = '{event_id}'
            """)
            conn.commit()
        except Exception as e:
            print(f"  PR open failed (non-fatal): {e}")
    else:
        print("  Skipping PR (set GITHUB_PAT env var + ensure branch_name is set)")

    # ── 5. Deploy new dbt version ─────────────────────────────
    print("\nDeploying new dbt project version...")
    try:
        dbt_deploy()
    except RuntimeError as e:
        msg = f"dbt deploy failed: {e}"
        print(f"{msg} \u2014 reverting files")
        for path, content in backups.items():
            with open(path, 'w') as f:
                f.write(content)
        if token and pr_url:
            post_pr_comment(token, pr_url, f"## \u274c dbt CI \u2014 Deploy Failed\n\n```\n{str(e)[:500]}\n```")
        return

    # ── 6. Run dbt against DEV ────────────────────────────────
    selector = f"source:bronze.{table_name}+"
    print(f"\nRunning dbt in DEV: --select {selector} --vars {{db_name: {DEV_DB}}}")
    passed, stdout = dbt_run(selector, DEV_DB)
    print(stdout[-1500:])

    # ── 7. Update test_status per model ───────────────────────
    model_results  = parse_model_results(stdout)
    overall_status = 'PASS' if passed else 'FAIL'
    err_excerpt    = '' if passed else stdout[-500:].replace("'", "''")

    for artifact_name, _, _, _ in artifacts:
        # Check per-model result first, fall back to overall
        model_status, detail = model_results.get(
            artifact_name, (overall_status, err_excerpt)
        )
        cur.execute(f"""
            UPDATE {PROD_DB}.CONFIG.GENERATED_CODE
            SET TEST_STATUS = '{model_status}',
                TEST_ERROR  = '{detail[:500].replace(chr(39), chr(39)+chr(39))}'
            WHERE EVENT_ID     = '{event_id}'
              AND ARTIFACT_NAME = '{artifact_name}'
        """)
        print(f"  {artifact_name}: {model_status}")

    conn.commit()

    # ── 8. Post CI result to PR + keep/revert files ───────────
    if not passed:
        print("\nTests FAILED — reverting model files")
        for path, content in backups.items():
            with open(path, 'w') as f:
                f.write(content)
        if token and pr_url:
            comment = f"""## \u274c dbt CI \u2014 Tests Failed

`dbt run` failed against `{DEV_DB}` (zero-copy clone of PROD).

This PR requires human review before merging.

```
{stdout[-800:]}
```

_Flagged by Snowflake schema drift pipeline \u2014 {change_type} on BRONZE.{table_name.upper()}_
"""
            try:
                post_pr_comment(token, pr_url, comment)
            except Exception as e:
                print(f"  PR comment failed (non-fatal): {e}")
        cur.execute(f"""
            UPDATE {PROD_DB}.CONFIG.SCHEMA_CHANGE_EVENTS
            SET pipeline_status = 'CI_FAILED'
            WHERE EVENT_ID = '{event_id}'
        """)
    else:
        print("\nTests PASSED — model files updated")
        if token and pr_url:
            comment = f"""## \u2705 dbt CI \u2014 All Tests Passed

`dbt run` completed successfully against `{DEV_DB}` (zero-copy clone of PROD).

- All impacted models materialised with no errors
- Schema change validated end-to-end through BRONZE \u2192 SILVER \u2192 GOLD
- Safe to merge

_Validated by Snowflake schema drift pipeline \u2014 {change_type} on BRONZE.{table_name.upper()}_
"""
            try:
                post_pr_comment(token, pr_url, comment)
            except Exception as e:
                print(f"  PR comment failed (non-fatal): {e}")
        cur.execute(f"""
            UPDATE {PROD_DB}.CONFIG.SCHEMA_CHANGE_EVENTS
            SET pipeline_status = 'CI_PASSED'
            WHERE EVENT_ID = '{event_id}'
        """)

    conn.commit()
    cur.close()
    conn.close()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 materialise_in_dev.py <event_id>")
        sys.exit(1)
    run(sys.argv[1])
